services:
  web-fe:
    # NOTE: Specify the Docker image to use for the web front-end
    build: .
    command: python app.py
    ports:
      - 5000:5000
  redis:
    image: "redis:alpine"
    ports:
      - 6379